src/main/java/com/mithun/contacts/entities/Office.java
package com.mithun.contacts.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

@Entity
public class Office extends BaseEntity {

	@Column
	private String name;

	@OneToOne
	private Address address;
	
	@ManyToOne
	private Company company;

	public Office() {
	}

	public Office(String name, Address address, Company company) {
		this.name = name;
		this.address = address;
		this.company = company;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

}

src/main/java/com/mithun/contacts/entities/UrlEntity.java
package com.mithun.contacts.entities;

import javax.persistence.MappedSuperclass;

@MappedSuperclass
public class UrlEntity extends BaseEntity{
	
	public String getUrl(){
		return getClass().getSimpleName().toLowerCase()+"?id="+getId();
	}

}

src/main/java/com/mithun/contacts/controllers/OfficeController.java
package com.mithun.contacts.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.mithun.contacts.entities.Address;
import com.mithun.contacts.entities.Company;
import com.mithun.contacts.entities.Office;
import com.mithun.contacts.repositories.CompanyRepository;
import com.mithun.contacts.repositories.OfficeRepository;

@Controller
public class OfficeController {

	@Autowired
	private OfficeRepository officeRepository;
	
	@Autowired
	private CompanyRepository companyRepository;

	@RequestMapping(value = "/office", params = "add", method = RequestMethod.GET)
	public String getAddOffice(@RequestParam("company_id") long companyId, Model model) {
		model.addAttribute("office", officeRepository.findOne(companyId));
		return "office/add";
	}

	@RequestMapping(value = "/office", params = "edit", method = RequestMethod.GET)
	public String getEditOffice(@RequestParam long id, Model model) {
		model.addAttribute("office", officeRepository.findOne(id));
		return "office/edit";
	}

	@RequestMapping(value = "/office", method = RequestMethod.GET)
	public String getViewOffice(@RequestParam long id, Model model) {
		model.addAttribute("office", officeRepository.findOne(id));
		return "office/view";
	}

	@RequestMapping(value = "/office", params = "add", method = RequestMethod.POST)
	public String postAddOffice(@RequestParam("company_id") long companyId, 
			@RequestParam String name,
			@RequestParam String street, @RequestParam String city,
			@RequestParam String state, @RequestParam String zip) {
		Address address = new Address(street, city, state, zip);
		Company company = companyRepository.findOne(companyId);
		Office office = new Office(name, address, company);
		office = officeRepository.save(office);
		return "redirect:office?id=" + office.getId();
	}

	@RequestMapping(value = "/office", params = "edit", method = RequestMethod.POST)
	public String postEditOffice(@RequestParam long id,
			@RequestParam String name, @RequestParam String street,
			@RequestParam String city, @RequestParam String state,
			@RequestParam String zip) {
		Office office = officeRepository.findOne(id);
		Address address = office.getAddress();
		office.setName(name);
		address.setStreet(street);
		address.setCity(city);
		address.setState(state);
		address.setZip(zip);
		officeRepository.save(office);
		return "redirect:office?id=" + office.getId();
	}

	@RequestMapping(value = "/office", params = "delete", method = RequestMethod.POST)
	public String postOffice(@RequestParam long id) {
		Office office = officeRepository.findOne(id);
		officeRepository.delete(office);
		return "redirect:" + office.getCompany().getUrl();
	}
}

src/main/webapp/view/office/add.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>add office</title>
</head>
<body>
	<h1>office</h1>
	<form action="office" method="post">
	<input type="hidden" name="add">
	<input type="hidden" name="company_id" value="${company.id}">
		<ul>
			<li>name : <input type="text" name="name"></li>
			<li>street : <input type="text" name="street"></li>
			<li>city : <input type="text" name="city"></li>
			<li>state : <input type="text" name="state"></li>
			<li>zip : <input type="text" name="zip"></li>
		</ul>
		<input type="submit" value="add">	
	</form>
	<a href="${company.url}">back to ${company.name}</a>
</body>
</html>

src/main/webapp/view/office/edit.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>edit office</title>
</head>
<body>
	<h1>office</h1>
	<form action="office" method="post">
	<input type="hidden" name="edit">
	<input type="hidden" name="id"  value="${office.id}">
		<ul>
			<c:set var="address" value="${office.address}"/>
			<li>name : <input type="text" name="name" value="${office.name}"></li>
			<li>street : <input type="text" name="street" value="${address.street}"></li>
			<li>city : <input type="text" name="city" value="${address.city}"></li>
			<li>state : <input type="text" name="state" value="${address.state}"></li>
			<li>zip : <input type="text" name="zip" value="${address.zip}"></li>
		</ul>
		<input type="submit" value="edit">	
	</form>
	<form action="office" method="post">
		<input type="hidden" name="delete"/>
		<input type="hidden" name="id" value="${office.id}"/>
		<input type="submit" name="delete" value="delete">
	</form>
	<a href="${office.company.url}">back to ${office.company.name}</a>
</body>
</html>

src/main/webapp/view/office/view.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<html>
<head>
<title>view offices</title>
</head>
<body>
	<h1>View office</h1>
	<input type="hidden" name="add">
	<h2>${office.name}</h2>
	<ul>
		<c:set var="address" value="${office.address}"/>
		<li>${address.street}</li>
		<li>${address.state} - ${address.zip}</li>
	</ul>
	<a href="contacts">back to contact list</a> |
	<a href="${office.url}&edit">Edit office</a> | 
</body>
</html>